face_tracker_node:
  ros__parameters:
    kp_yaw: 0.05
    ki_yaw: 0.0
    kd_yaw: 0.003
    kp_height: 0.05
    ki_height: 0.0
    kd_height: 0.003
    kp_dist: 0.01
    ki_dist: 0.0
    kd_dist: 0.002
    target_face_width: 150
    cascade_path: "/usr/share/opencv4/haarcascades/haarcascade_frontalface_default.xml"
    min_height: 0.3
    max_height: 4.0
    max_xy_range: 15.0
